import re
f=open('phone.txt')
string=f.read()
f.close()
result_1=re.findall(r".+ (.+)\t\(\d\d0\)\s(.+)",string)
#print(result_1)
result_2=re.findall(r".+\t\((\d{3})\)\s.{7}7",string)
#print(result_2)
result_3=re.findall(r'(.+)\t\(\d\d\d\) [13579].{7}',string)
#print(result_3)
result_4=re.findall(r'(.+) .+\t\([0-2][0-9][0-9]\)\s.+',string)
#print(result_4)
result_5=re.findall(r'(.+) .+[aeiou]\t\(\d{3}\) .{7}[079]',string)
print(result_5)